### ISSUE TITLE
Handle emojis from other servers properly

### ISSUE THREAD

**Issue by Runebreaker** [Runebreaker/RuneBotKt#18]
For the 'what' command, don't default to eggplant, but either do nothing, give message stating the emoji is from another server or react to command message with an X.

**Comment by Jagenka** [comment]
Again, there are no "emoji from other servers". This makes no sense.

**Comment by Runebreaker** [comment]
bruh, you know what is meant

**Comment by Jagenka** [comment]
😤

**Comment by Jagenka** [comment]
should be implemented in 722bc7cf75638abd24004cb38b7911ea91d3264f
